name: build and publish wdi5 TS sample app to BTP

on:
  push:
    branches:
      - main
    paths:
      - "examples/ui5-ts-app/**"

jobs:
  build-sample-ts-app:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: "npm"
          cache-dependency-path: "**/package-lock.json"
          registry-url: https://registry.npmjs.org/
      - run: npm ci
      - run: |
          cd examples/ui5-ts-app
          npm run build:cf
      # let's check where we are
      - run: pwd
      - name: provide mtar
        uses: actions/upload-artifact@v3
        with:
          name: mtar
          path: examples/ui5-ts-app/mta_archives/ui5-approuter_1.0.0.mtar

  publish-sample-ts-app-to-btp:
    needs: build-sample-ts-app
    runs-on: ubuntu-latest
    steps:
      - name: get mtar
        uses: actions/download-artifact@v3
        with:
          name: mtar
      - name: deploy to BTP
        uses: elliottpope/cloudfoundry-cli-action@v6
        with:
          CF_API: https://api.cf.eu20.hana.ondemand.com
          USERNAME: ${{ secrets.BTP_LOGIN }}
          PASSWORD: ${{ secrets.BTP_PASSWORD }}
          ORG: ${{secrets.BTP_ORG}}
          SPACE: ${{secrets.BTP_SPACE}}
          COMMAND: deploy examples/ui5-ts-app/mta_archives/ui5-approuter_1.0.0.mtar -f
